AggregatorApp/urls.py
from django.urls import path, include
from . import views
from django.contrib.auth import views as auth_views
from django.contrib.auth.decorators import login_required
from .views import (SignIn, NewsDetail, SavedNewsDetail)

app_name = 'AggregatorApp'
urlpatterns = [
    path('', views.index, name='index'),

    path('accounts/', include('django.contrib.auth.urls')),
    path('change-password/', auth_views.PasswordChangeView.as_view(
        template_name='AggregatorApp/change-password.html',
        success_url='/'
    ),
         name='change_password'
         ),

    path('sign-up/', views.signup, name='sign-up'),
    path('sign-in/', SignIn.as_view(), name='sign-in'),
    path('profile/', views.view_profile, name='profile'),
    path('profile/update/', views.update_profile, name='update-profile'),

    path('process-news/', views.news_processing, name='process-news'),
    # path('news-detail/<int:year>/<int:month>/<int:day>/<news_id>/<pk>', NewsDetail.as_view(), name='news-detail'),
    path('<int:year>/<int:month>/<int:day>/<news_id>/<pk>', views.news_detail, name='news-detail'),

    path('category/<str:section>/', views.category, name='category'),
    path('source/<str:source>/', views.news_by_source, name='news-by-source'),
    path('tag/<slug:tag_slug>/', views.news_by_tag, name='news_list_by_tag'),
    path('date/<str:date>/', views.news_by_date, name='news-by-date'),
    path('author/<str:author>/', views.news_by_author, name='news-by-author'),

    path('add-tag/<slug:tag_slug>/', views.add_tags, name='add-tag'),
    path('view-tags/', views.added_tags_list, name='added-tags-list'),
    path('remove-tag/<slug:tag_slug>/', views.remove_tags, name='remove-tag'),
    path('user-feed/', views.user_feed, name='user-feed'),

    path('add-news/<pk>', views.save_news, name='save-news'),
    path('saved-news/', views.saved_news_list_view, name='saved-news'),
    path('saved-news-detail/<int:id>/<int:year>/<int:month>/<int:day>/<pk>', login_required(SavedNewsDetail.as_view()),
         name='saved-news-detail'),
    path('saved-news-delete/<pk>', views.saved_news_delete, name='saved-news-delete'),

    path('block-source/<str:source>', views.block_source, name='block-source'),
    path('blocked-sources/', views.blocked_sources_list, name='blocked-sources-list'),
    path('unblock-source/<pk>', views.unblock_source, name='unblock-source'),
]

News_Aggregator/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView
from django.conf.urls import url

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('AggregatorApp.urls')),
    # url(r'^favicon\.ico$', RedirectView.as_view(url='/static/images/favicon.ico')),
]

AggregatorApp/models.py
# from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
from djongo import models
from django_countries.fields import CountryField
from django.db.models.signals import post_save
from django.dispatch import receiver
from taggit.managers import TaggableManager
from taggit.models import Tag


class Profile(models.Model):
    GENDER_CHOICES = (
        ('Male', 'Male'),
        ('Female', 'Female'),
        ('Other', 'Other'),
        ('Not to Specify', 'Not to Specify')
    )

    user = models.OneToOneField(User, on_delete=models.CASCADE)
    birth_date = models.DateField(null=True, blank=True)
    gender = models.CharField(max_length=15, choices=GENDER_CHOICES, default='Not to Specify')
    bio = models.TextField(max_length=500, blank=True)
    country = CountryField(blank_label='(Select Country)', blank=True)
    tag = models.ManyToManyField('taggit.Tag', blank=True)

    def __str__(self):
        return self.user.username


@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)


@receiver(post_save, sender=User)
def save_user_profile(sender, instance, **kwargs):
    instance.profile.save()


class BlockedSources(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    source_name = models.CharField(max_length=100)
    source_url = models.CharField(max_length=300)

    def __str__(self):
        return self.source_name


class RawNews(models.Model):
    _id = models.ObjectIdField()
    source = models.CharField(max_length=50)
    headline = models.CharField(max_length=255)
    author = models.CharField(max_length=200)
    date_time = models.CharField(max_length=255)
    content = models.JSONField()
    url = models.CharField(max_length=255)
    tags = models.JSONField()
    section = models.CharField(max_length=100)
    image = models.CharField(max_length=255)
    description = models.TextField()

    def __str__(self):
        return self.headline


class News(models.Model):
    source = models.CharField(max_length=50)
    news_id = models.CharField(max_length=20, unique=True)
    headline = models.CharField(max_length=255)
    author = models.CharField(max_length=200)
    date_time = models.DateField()
    content = models.JSONField()
    url = models.CharField(max_length=255)
    tags = TaggableManager()
    section = models.CharField(max_length=100, null=True, blank=True)
    image = models.CharField(max_length=255, null=True, blank=True)
    description = models.TextField(null=True, blank=True)

    def __str__(self):
        return self.headline

    def get_absolute_url(self):
        return reverse('AggregatorApp:news-detail',
                       args=[self.date_time.year, self.date_time.month, self.date_time.day, self.news_id, self.pk])


class SavedNews(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    source = models.CharField(max_length=50)
    headline = models.CharField(max_length=255)
    author = models.CharField(max_length=200)
    date_time = models.DateField()
    content = models.JSONField()
    url = models.CharField(max_length=255)
    tags = TaggableManager()
    section = models.CharField(max_length=100, null=True, blank=True)
    image = models.CharField(max_length=255, null=True, blank=True)
    description = models.TextField(null=True, blank=True)

    def __str__(self):
        return self.headline

    def get_absolute_url(self):
        return reverse('AggregatorApp:saved-news-detail',
                       args=[self.user.id, self.date_time.year, self.date_time.month, self.date_time.day, self.pk])


class Comment(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    news = models.ForeignKey(News, on_delete=models.CASCADE, related_name='comments')
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=True)

    class Meta:
        ordering = ('created',)

    def __str__(self):
        return f'Comment by {self.user.username} on {self.news.headline}'

AggregatorApp/forms.py
from django import forms
from django.forms import ModelForm
from .models import Profile, Comment
from django.contrib.auth.models import User


class UserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'email')


class DateInput(forms.DateInput):
    input_type = 'date'


class ProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ('birth_date', 'gender', 'bio', 'country')
        widgets = {'birth_date': DateInput()}


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('body',)

AggregatorApp/views.py
from django.contrib.auth import authenticate, login
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponse
import requests, json
# from .forms import UserRegistrationForm
from .models import RawNews, Profile, News, BlockedSources, SavedNews, Comment
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from .forms import UserForm, ProfileForm, CommentForm
from django.contrib.auth import views as auth_views
from django.views.generic import ListView, DetailView, DeleteView
from taggit.models import Tag, TaggedItem
from django.db.models import Count
from django.contrib import messages
from django.contrib.auth.decorators import login_required, user_passes_test
from django.contrib.admin.views.decorators import staff_member_required
from django.utils.dateparse import parse_date


def index(request):
    object_list = News.objects.all()
    section = 'index'

    popular_tag = get_object_or_404(Tag, slug='ap-top-news')
    pop = News.objects.filter(tags__in=[popular_tag])
    cul = News.objects.filter(section='Culture')
    opi = News.objects.filter(section='Opinion')
    oth = News.objects.filter(section='Other')

    try:
        popular_news = remove_blocked_sources(pop, request.user)
        cultural_news = remove_blocked_sources(cul, request.user)
        opinion_news = remove_blocked_sources(opi, request.user)
        other_news = remove_blocked_sources(oth, request.user)
    except:
        popular_news = set(pop)
        cultural_news = set(cul)
        opinion_news = set(opi)
        other_news = set(oth)
        print('Invalid user.')

    return render(request, 'AggregatorApp/index.html',
                  {'section': section, 'popular_news': popular_news, 'cultural_news': cultural_news,
                   'opinion_news': opinion_news, 'other_news': other_news})


def signup(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=raw_password)
            login(request, user)
            return redirect('AggregatorApp:index')
        else:
            messages.error(request, 'Please enter the data according to the guidelines below.')
    else:
        form = UserCreationForm()
    return render(request, 'AggregatorApp/sign-up.html', {'form': form})


class SignIn(auth_views.LoginView):
    template_name = 'AggregatorApp/sign-in.html'


def view_profile(request):
    profile = Profile.objects.get(user=request.user)

    return render(request, 'AggregatorApp/profile-view.html', {'profile': profile})


@login_required(login_url='/sign-in/')
def update_profile(request):
    if request.method == 'POST':
        user_form = UserForm(request.POST, instance=request.user)
        profile_form = ProfileForm(request.POST, instance=request.user.profile)
        if user_form.is_valid() and profile_form.is_valid():
            user_form.save()
            profile_form.save()
            print('Your profile was successfully updated!')
            return redirect('AggregatorApp:profile')
        else:
            print('Please correct the error below.')
    else:
        user_form = UserForm(instance=request.user)
        profile_form = ProfileForm(instance=request.user.profile)
    return render(request, 'AggregatorApp/profile-update.html', {
        'user_form': user_form,
        'profile_form': profile_form,
    })


@staff_member_required()
def news_processing(request):
    news = RawNews.objects.all()
    c = 0

    for n in news:
        c = c + 1
        source = n.source
        date_time = n.date_time
        section = n.section
        if section:
            s = section.lower()
        else:
            s = 'none'
        news_id = ''

        if source == 'AP News':
            news_id = "AP-News-" + str(c)

            if s == 'u.s. news' or s == 'world news':
                section = 'World'
            elif s == 'technology' or s == 'science':
                section = 'Science and Technology'
            elif s == 'religion' or s == 'travel' or s == 'lifestyle':
                section = 'Culture'
            elif s == 'oddities':
                section = 'Other'
            elif s == 'ap fact check':
                section = 'Opinion'
            for t in n.tags:
                if t.lower() == 'sport' or t.lower() == 'sports':
                    section = 'Sports'
                if t.lower() == 'politics':
                    section = 'Politics'

        elif source == 'The Guardian':
            news_id = "Guardian-" + str(c)

            if s == 'sports' or s == 'football' or s == 'sport':
                section = 'Sports'
            elif s == 'money' or s == 'business':
                section = 'Business'
            elif s == 'technology' or s == 'science':
                section = 'Science and Technology'
            elif s == 'music' or s == 'books' or s == 'film' or s == 'fashion' or s == 'stage' or s == 'games':
                section = 'Entertainment'
            elif s == 'society' or s == 'culture' or s == 'art and design' or s == 'travel' or s == 'food' or s == 'life and style':
                section = 'Culture'
            elif s == 'opinion':
                section = 'Opinion'
            elif s == 'world news' or s == 'us news' or s == 'uk news' or s == 'australia news' or s == 'global development':
                section = 'World'
            elif s == 'politics':
                section = 'Politics'
            elif s == 'environment':
                section = 'Environment'
            elif s == 'education' or s == 'television & radio' or s == 'media' or s == 'none' or s == 'info':
                section = 'Other'
            else:
                section = 'Other'

        elif source == 'Reuters':
            news_id = "Reuters-" + str(c)

            if s == 'technology':
                section = 'Science and Technology'
            if s == 'markets':
                section = 'Business'
            if s == 'lifestyle':
                section = 'Culture'
            for t in n.tags:
                if t.lower() == 'sport':
                    section = 'Sports'
                elif 'entertainment' in t.lower():
                    section = 'Entertainment'

        date = date_time[0:10]
        print(news_id)
        print(n.headline)

        if n.content and n.headline:
            news2 = News(source=source, news_id=news_id,
                         headline=n.headline, author=n.author,
                         date_time=date, url=n.url, content=n.content,
                         section=section, image=n.image, description=n.description)

            news2.save()

            for t in n.tags:
                try:
                    news2.tags.add(t.lower())
                except:
                    news2.tags.add('-')

                news2.save()

    print("Successful")

    return redirect('AggregatorApp:index')


def sidebar_news(object_list, user):
    popular_news_list = []
    opinion_news_list = []
    cultural_news_list = []
    other_news_list = []

    popular_tag = get_object_or_404(Tag, slug='ap-top-news')
    pop = News.objects.filter(tags__in=[popular_tag])
    opi = News.objects.filter(section='Opinion')
    cul = News.objects.filter(section='Culture')
    oth = News.objects.filter(section='Other')

    blocked_sources = []
    blocked_all = []
    try:
        blocked_all = BlockedSources.objects.filter(user=user)
    except:
        print('Invalid user')

    for b in blocked_all:
        blocked_sources.append(b.source_name)

    for item in pop:
        if item not in object_list and item.source not in blocked_sources:
            popular_news_list.append(item)

    for item in opi:
        if item not in object_list and item.source not in blocked_sources:
            opinion_news_list.append(item)

    for item in cul:
        if item not in object_list and item.source not in blocked_sources:
            cultural_news_list.append(item)

    for item in oth:
        if item not in object_list and item.source not in blocked_sources:
            other_news_list.append(item)

    popular_news = list(set(popular_news_list))
    opinion_news = list(set(opinion_news_list))
    cultural_news = list(set(cultural_news_list))
    other_news = list(set(other_news_list))

    return popular_news, opinion_news, cultural_news, other_news


def remove_blocked_sources(object_list, user):
    blocked_sources = []
    blocked_all = BlockedSources.objects.filter(user=user)
    print(blocked_all)
    for b in blocked_all:
        blocked_sources.append(b)

    if blocked_sources:
        print(blocked_sources)
        ol = object_list.exclude(source__in=blocked_sources)
        object_list = set(ol)
        print(object_list)
    else:
        ol = object_list
        object_list = set(ol)
        print(object_list)

    return object_list


def news_by_tag(request, tag_slug=None):
    object_list = News.objects.all()
    tag = None

    if tag_slug:
        tag = get_object_or_404(Tag, slug=tag_slug)
        object_list = object_list.filter(tags__in=[tag])

    try:
        object_list = remove_blocked_sources(object_list, request.user)
    except:
        print('Invalid user.')

    side_news = sidebar_news(object_list, request.user)
    popular_news = side_news[0]
    opinion_news = side_news[1]
    cultural_news = side_news[2]

    return render(request, 'AggregatorApp/saved-news.html',
                  {'object_list': object_list, 'tag': tag, 'popular_news': popular_news, 'opinion_news': opinion_news,
                   'cultural_news': cultural_news})


def news_by_source(request, source):
    object_list = News.objects.filter(source__in=[source])
    s = source
    blocked = ''

AggregatorApp/templates/AggregatorApp/index.html
{% extends 'AggregatorApp/base.html' %}
{% load static %}

{% block title %}Index{% endblock %}

{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-md-8">
                <div class="entity_wrapper">

                    <div class="entity_title header_purple">
                        <h1>Index</h1>
                    </div>
                    <!-- entity_title -->

                </div>


                <div class="category_section camera">
                    <!-- article_title -->
                    {% for news in popular_news %}
                        <div class="category_article_wrapper">
                            <div class="row">
                                <div class="col-md-5">

                                    <div class="top_article_img">
                                        <a href="{{ news.get_absolute_url }}" target="_self">
                                            <img class="img-responsive" src="{{ news.image }}" alt="feature-top">
                                        </a>
                                    </div>
                                    <!-- top_article_img -->

                                </div>
                                <div class="col-md-7">
                                    <span class="tag orange">{{ news.section }}</span>

                                    <div class="category_article_title">
                                        <h2><a href="{{ news.get_absolute_url }}"
                                               target="_blank">{{ news.headline }}</a></h2>
                                    </div>
                                    <!-- category_article_title -->

                                    <div class="article_date">
                                        Source: <a
                                            href="{% url 'AggregatorApp:news-by-source' news.source %}"> {{ news.source }}</a>&nbsp
                                        Date: <a
                                            href="{% url 'AggregatorApp:news-by-date' news.date_time %}"> {{ news.date_time }}</a>&nbsp
                                        Author: <a
                                            href="{% url 'AggregatorApp:news-by-author' news.author %}"> {{ news.author }}</a>
                                    </div>
                                    <!----article_date------>
                                    <!-- category_article_wrapper -->

                                    <div class="category_article_content">
                                        {{ news.description }}
                                    </div>
                                    <!-- category_article_content -->
                                </div>
                                <!-- col-md-7 -->
                            </div>
                            <!-- row -->
                            <hr>
                        </div>
                        <!-- category_article_wrapper -->
                    {% endfor %}
                </div>
            </div>
            <!-- col-md-8 -->

            {% include 'AggregatorApp/parts/side-bar-category.html' %}
            <!-- col-md-4 -->
        </div>
        <!-- row -->
    </div>
    <!-- container -->
{% endblock %}

AggregatorApp/templates/AggregatorApp/saved-news-detail.html
{% extends 'AggregatorApp/base.html' %}

{% block css-head %}
    <style>
        .entity_footer {
            border-bottom: 0px;
        }

        .tag {
            margin-top: 5px;
        }
    </style>
{% endblock %}

{% block title %}{{ savednews.headline }}{% endblock %}

{% block content %}
    <section id="entity_section" class="entity_section">

        <div class="container">
            <div class="row">

                <div class="col-md-8">
                    <div class="entity_wrapper">

                        <div class="entity_title">
                            <h1>{{ savednews.headline }}</h1>
                            <a href="#" data-toggle="modal" data-target="#deleteConfirmationModal"
                               class="btn btn-danger">Delete</a>
                        </div>
                        <!-- entity_title -->

                        <div class="entity_meta">
                            Source: <a
                                href="{% url 'AggregatorApp:news-by-source' savednews.source %}"> {{ savednews.source }}</a>&nbsp
                            Date: <a
                                href="{% url 'AggregatorApp:news-by-date' savednews.date_time %}"> {{ savednews.date_time }}</a>&nbsp
                            Author: <a
                                href="{% url 'AggregatorApp:news-by-author' savednews.author %}"> {{ savednews.author }}</a>&nbsp;

                            {% if news.section == 'Science and Technology' %}
                                Section:
                                <a href="{% url 'AggregatorApp:category' 'science-technology' %}"> {{ savednews.section }}</a>
                            {% else %}
                                Section:
                                <a href="{% url 'AggregatorApp:category' savednews.section.lower %}"> {{ savednews.section }}</a>
                            {% endif %}
                        </div>
                        <!-- entity_meta -->

                        <div class="entity_rating"></div>
                        <!-- entity_rating -->

                        <div class="entity_thumb">
                            <img class="img-responsive" src="{{ savednews.image }}" alt="feature-top">
                        </div>
                        <!-- entity_thumb -->

                        <div class="entity_content">
                            {% for con in savednews.content %}
                                <p class="text-justify">{{ con }}</p>
                            {% endfor %}
                        </div>
                        <!-- entity_content -->

                        <div class="entity_footer">
                            <div class="entity_tag">
                                <div class="dropdown">
                                    {% for tag in savednews.tags.all %}
                                        {% if tag.name != '-' %}
                                            <span class="tag">
                                                <a href="{% url 'AggregatorApp:news_list_by_tag' tag.slug %}">
                                                    {{ tag.name }}
                                                </a>&nbsp
                                                <a href="{% url 'AggregatorApp:add-tag' tag.slug %}">
                                                    <i class="fa fa-plus"></i>
                                                </a>
                                        </span>
                                        {% endif %}
                                    {% endfor %}
                                </div>
                            </div>
                            <!-- entity_tag -->
                        </div>
                        <!-- entity_footer -->
                    </div>
                    <!-- entity_wrapper -->
                    <br/>
                    <hr>

                    <div class="related_news">
                        <div class="entity_inner__title header_purple">
                            <h2><a href="#">Related News</a></h2>
                        </div>
                        <!-- entity_title -->

                        <div class="row">
                            <div class="col-md-6">
                                <div class="media">
                                    <div class="media-left">
                                        <a href="#"><img class="media-object" src="assets/img/cat-mobi-sm1.jpg"
                                                         alt="Generic placeholder image"></a>
                                    </div>
                                    <div class="media-body">
                                        <span class="tag purple"><a href="category.html"
                                                                    target="_self">Mobile</a></span>

                                        <h3 class="media-heading"><a href="single.html" target="_self">Apple launches
                                            photo-centric wrist
                                            watch for Android</a></h3>
                                        <span class="media-date"><a href="#">10Aug- 2015</a>,  by: <a
                                                href="#">Eric joan</a></span>

                                        <div class="media_social">
                                            <span><a href="#"><i class="fa fa-share-alt"></i>424</a> Shares</span>
                                            <span><a href="#"><i class="fa fa-comments-o"></i>4</a> Comments</span>
                                        </div>
                                    </div>
                                </div>
                                <div class="media">
                                    <div class="media-left">
                                        <a href="#"><img class="media-object" src="assets/img/cat-mobi-sm3.jpg"
                                                         alt="Generic placeholder image"></a>
                                    </div>
                                    <div class="media-body">
                                        <span class="tag purple"><a href="category.html"
                                                                    target="_self">Mobile</a></span>

                                        <h3 class="media-heading"><a href="single.html" target="_self">The Portable
                                            Charger or data
                                            cable</a></h3>
                                        <span class="media-date"><a href="#">10Aug- 2015</a>,  by: <a
                                                href="#">Eric joan</a></span>

                                        <div class="media_social">
                                            <span><a href="#"><i class="fa fa-share-alt"></i>424</a> Shares</span>
                                            <span><a href="#"><i class="fa fa-comments-o"></i>4</a> Comments</span>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="media">
                                    <div class="media-left">
                                        <a href="#"><img class="media-object" src="assets/img/cat-mobi-sm2.jpg"
                                                         alt="Generic placeholder image"></a>
                                    </div>
                                    <div class="media-body">
                                        <span class="tag purple"><a href="category.html"
                                                                    target="_self">Mobile</a></span>

                                        <h3 class="media-heading"><a href="single.html" target="_self">Iphone 6 launches
                                            white & Grey
                                            colors handset</a></h3>
                                        <span class="media-date"><a href="#">10Aug- 2015</a>,  by: <a
                                                href="#">Eric joan</a></span>

                                        <div class="media_social">
                                            <span><a href="#"><i class="fa fa-share-alt"></i>424</a> Shares</span>
                                            <span><a href="#"><i class="fa fa-comments-o"></i>4</a> Comments</span>
                                        </div>
                                    </div>
                                </div>
                                <div class="media">
                                    <div class="media-left">
                                        <a href="#"><img class="media-object" src="assets/img/cat-mobi-sm4.jpg"
                                                         alt="Generic placeholder image"></a>
                                    </div>
                                    <div class="media-body">
                                        <span class="tag purple"><a href="category.html"
                                                                    target="_self">Mobile</a></span>
                                        <a href="single.html" target="_self"><h3 class="media-heading">Fully new look
                                            slim handset
                                            like</h3></a>
                                        <span class="media-date"><a href="#">10Aug- 2015</a>,  by: <a
                                                href="#">Eric joan</a></span>

                                        <div class="media_social">
                                            <span><a href="#"><i class="fa fa-share-alt"></i>424</a> Shares</span>
                                            <span><a href="#"><i class="fa fa-comments-o"></i>4</a> Comments</span>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <!-- Related news -->
                </div>
                <!--Left Section-->

                {% include 'AggregatorApp/parts/side-bar-category.html' %}
                <!-- row -->

            </div>
            <!-- container -->
        </div>

    </section>
    <!-- Entity Section Wrapper -->
    {% include 'AggregatorApp/parts/delete-confirmation-modal.html' %}
{% endblock %}